name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create release directory
        run: mkdir -p release/${{ env.VERSION }}

      - name: Build Windows client
        run: |
          cd source
          GOOS=windows GOARCH=amd64 go build -o "../release/${{ env.VERSION }}/openp2p-windows-amd64.exe" ./cmd/openp2p.go
          cd ..

      - name: Build Linux client
        run: |
          cd source
          GOOS=linux GOARCH=amd64 go build -o "../release/${{ env.VERSION }}/openp2p-linux-amd64" ./cmd/openp2p.go
          cd ..

      - name: Build macOS client
        run: |
          cd source
          GOOS=darwin GOARCH=amd64 go build -o "../release/${{ env.VERSION }}/openp2p-macos-amd64" ./cmd/openp2p.go
          cd ..

      - name: Copy documentation and config files
        run: |
          cp README.md "release/${{ env.VERSION }}/"
          cp VERSION.md "release/${{ env.VERSION }}/"
          cp 客户端安装指南.md "release/${{ env.VERSION }}/"
          cp source/config.json.example "release/${{ env.VERSION }}/config.json"

      - name: Create ZIP archives
        run: |
          cd "release/${{ env.VERSION }}"
          zip -r "../openp2p-windows-amd64-${{ env.VERSION }}.zip" openp2p-windows-amd64.exe README.md VERSION.md 客户端安装指南.md config.json
          zip -r "../openp2p-linux-amd64-${{ env.VERSION }}.zip" openp2p-linux-amd64 README.md VERSION.md 客户端安装指南.md config.json
          zip -r "../openp2p-macos-amd64-${{ env.VERSION }}.zip" openp2p-macos-amd64 README.md VERSION.md 客户端安装指南.md config.json
          cd ../..

      - name: Create release notes
        run: |
          cat > "release/release_notes_${{ env.VERSION }}.md" << EOF
          # OpenP2P ${{ env.VERSION }} 发布说明
          
          ## 更新内容
          
          - 修复了 TOTP 验证问题，增加了时间偏移容忍度
          - 优化了项目结构，删除了废弃的文件和脚本
          - 其他 bug 修复和性能优化
          
          ## 下载
          
          - [Windows 64位](openp2p-windows-amd64-${{ env.VERSION }}.zip)
          - [Linux 64位](openp2p-linux-amd64-${{ env.VERSION }}.zip)
          - [macOS 64位](openp2p-macos-amd64-${{ env.VERSION }}.zip)
          
          ## 安装说明
          
          请参考压缩包中的 \`客户端安装指南.md\` 文件。
          
          ## 配置说明
          
          默认配置文件为 \`config.json\`，您可以根据需要修改。
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/openp2p-windows-amd64-${{ env.VERSION }}.zip
            release/openp2p-linux-amd64-${{ env.VERSION }}.zip
            release/openp2p-macos-amd64-${{ env.VERSION }}.zip
          body_path: release/release_notes_${{ env.VERSION }}.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 