name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/openp2p-windows-amd64-${{ env.VERSION }}.zip
          asset_name: openp2p-windows-amd64-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/openp2p-linux-amd64-${{ env.VERSION }}.zip
          asset_name: openp2p-linux-amd64-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload macOS Intel Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/openp2p-macos-amd64-${{ env.VERSION }}.zip
          asset_name: openp2p-macos-amd64-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload macOS Apple Silicon Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/openp2p-macos-arm64-${{ env.VERSION }}.zip
          asset_name: openp2p-macos-arm64-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Create release directory
        run: mkdir -p release/${{ env.VERSION }}

      - name: Build Windows client
        run: |
          cd source
          GOOS=windows GOARCH=amd64 go build -o "../release/${{ env.VERSION }}/openp2p-windows-amd64.exe" ./cmd/openp2p.go
          cd ..

      - name: Build Linux client
        run: |
          cd source
          GOOS=linux GOARCH=amd64 go build -o "../release/${{ env.VERSION }}/openp2p-linux-amd64" ./cmd/openp2p.go
          cd ..

      - name: Build macOS client
        run: |
          cd source
          GOOS=darwin GOARCH=amd64 go build -o "../release/${{ env.VERSION }}/openp2p-macos-amd64" ./cmd/openp2p.go
          GOOS=darwin GOARCH=arm64 go build -o "../release/${{ env.VERSION }}/openp2p-macos-arm64" ./cmd/openp2p.go
          cd ..

      - name: Copy documentation and config files
        run: |
          cp README.md "release/${{ env.VERSION }}/"
          cp VERSION.md "release/${{ env.VERSION }}/"
          cp 客户端安装指南.md "release/${{ env.VERSION }}/"
          cp source/config.json.example "release/${{ env.VERSION }}/config.json"

      - name: Create ZIP archives
        run: |
          cd "release/${{ env.VERSION }}"
          zip -r "../openp2p-windows-amd64-${{ env.VERSION }}.zip" openp2p-windows-amd64.exe README.md VERSION.md 客户端安装指南.md config.json
          zip -r "../openp2p-linux-amd64-${{ env.VERSION }}.zip" openp2p-linux-amd64 README.md VERSION.md 客户端安装指南.md config.json
          zip -r "../openp2p-macos-amd64-${{ env.VERSION }}.zip" openp2p-macos-amd64 README.md VERSION.md 客户端安装指南.md config.json
          zip -r "../openp2p-macos-arm64-${{ env.VERSION }}.zip" openp2p-macos-arm64 README.md VERSION.md 客户端安装指南.md config.json
          cd ../..

      - name: Create release notes
        run: |
          cat > "release/release_notes_${{ env.VERSION }}.md" << EOF
          # OpenP2P ${{ env.VERSION }} 发布说明
          
          ## 更新内容
          
          - 新增对Apple Silicon（M1/M2芯片）的支持
          - 修复了用户信息页面问题，支持显示和修改用户信息
          - 修复了节点管理功能，支持添加、编辑和删除节点
          - 优化了客户端配置，移除了不必要的字段
          - 添加了详细的客户端配置文档
          - 其他 bug 修复和性能优化
          
          ## 下载
          
          - [Windows 64位](openp2p-windows-amd64-${{ env.VERSION }}.zip)
          - [Linux 64位](openp2p-linux-amd64-${{ env.VERSION }}.zip)
          - [macOS Intel芯片](openp2p-macos-amd64-${{ env.VERSION }}.zip)
          - [macOS Apple芯片](openp2p-macos-arm64-${{ env.VERSION }}.zip)
          
          ## 安装说明
          
          请参考压缩包中的 \`客户端安装指南.md\` 文件。
          
          ## 配置说明
          
          默认配置文件为 \`config.json\`，您可以根据需要修改。
          主要配置项说明：
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/openp2p-windows-amd64-${{ env.VERSION }}.zip
            release/openp2p-linux-amd64-${{ env.VERSION }}.zip
            release/openp2p-macos-amd64-${{ env.VERSION }}.zip
            release/openp2p-macos-arm64-${{ env.VERSION }}.zip
          body_path: release/release_notes_${{ env.VERSION }}.md
          token: ${{ secrets.GITHUB_TOKEN }}